#This file has full set of effects in the observed CMB
name: cmbs4
title: '$[\widehat{\alpha}\widehat{\phi}]^{D}[\alpha, \phi]$'
k: "ptt"
itmax: 5
imin: 1
imax: 1
v: "p_check"
joint_module: false
do_mf: false #can leave this to false for now, till easier version to use is released
getrdn0: false #can leave this to false for now, till easier version to use is released
cmb_version: "p_check"
selected: ["p"] #ad would give a but disabled.
cmbchain: ["p"]
tol: 6
beam: 1.0
nlev_t: 1.0
lmax_ivf: 4096
mmax_ivf: 4000
lmin_tlm: 10
lmin_elm: 30
lmin_blm: 30
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
#no_tau: true
#no_curl: true
# Binning parameters
binning:
  lmin: 20
  lmax: 4000
  delta: 40