#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation and lensing effects.
title: '$[\widehat{\alpha}\widehat{\phi}]^{R,D}[\alpha, \phi]$'
k: "p_p"
itmax: 15
imin: 0
imax: 0
v: "experiment_full_alpha_non_disabled_phi_omega_rec_only"
joint_module: true
cmb_version: "experiment_full"
selected: ["a", "p", "o"] # ad would give a but disabled.
tol: 6
beam: 1.0
nlev_t: 0.35
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30
lmin_blm: 100
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
