#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation effect.
title: '$[\widehat{\alpha}]^{R}[\alpha, \phi]$'
k: "p_p"
itmax: 12
imin: 0
imax: 15
v: "all_cmb_check"
joint_module: true
cmb_version: "all_cmb"
selected: ["a", "f", "p", "o"]
tol: 6
beam: 1.0
nlev_t: 0.35
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30
lmin_blm: 100
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
