#This file has alpha as an effect in the observed CMB
#and it only reconstructs the rotation effect.
title: '$[\widehat{\alpha}]^{R}[\alpha]$'
k: "p_p"
itmax: 5 #it converges quite quickly
imin: 0
imax: 0
v: "experiment_alpha_alpha_rec_only"
joint_module: true
cmb_version: "experiment_alpha"
no_lensing: true
no_curl: true
no_tau: true
selected: "a" # ad would give a but disabled.
tol: 6
beam: 1.0
nlev_t: 0.35
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30 #it was 2
lmin_blm: 100 #it was 2
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
