#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation and lensing effects.
#the rotation effect is disabled as an operator
title: '$[\widehat{\alpha}\widehat{\phi}]^{D}[\alpha, \phi]$'
k: "p_p"
itmax: 30
imin: 0
imax: 0
do_mf: false
getrdn0: true
v: "p1" #should have been disabled :p
joint_module: true
cmb_version: "po_only"
selected: ["p", "o"] #ad would give a but disabled.
cmbchain: ["p", "o"]
tol: 6
beam: 1.0
nlev_t: 1.0
lmax_ivf: 5000
mmax_ivf: 5000
lmin_elm: 30
lmin_blm: 30
lmax_unl: 5000
mmax_unl: 5000
lmax_qlm: 5000
mmax_qlm: 5000
#no_tau: true
#no_curl: true
# Binning parameters
binning:
  lmin: 20
  lmax: 4000
  delta: 40