#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation and lensing effects.
#the rotation effect is disabled as an operator
title: '$[\widehat{\alpha}\widehat{\phi}]^{D}[\alpha, \phi]$'
k: "p_p"
itmax: 20 
imin: 0
imax: 3
do_mf: false
getrdn0: true
Lmin: 2
v: "a_o__6" #"a_o_small_1" #should have been disabled :p
joint_module: true
cmb_version: "a_new"
selected: ["a", "o"] #ad would give a but disabled.
cmbchain: ["a"]
tol: 6
beam: 1.0
nlev_t: 1.0
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30
lmin_blm: 100
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
#no_tau: true
#no_curl: true
# Binning parameters
binning:
  lmin: 20
  lmax: 4000
  delta: 40