#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation and lensing effects.
#the rotation effect is disabled as an operator
title: '$[\widehat{\alpha}\widehat{\phi}]^{D}[\alpha, \phi]$'
k: "p_p"
itmax: 15
imin: 0
imax: 127
do_mf: False
v: "apo_new_official_check_factor_2_vofficial_no_alpha" #should have been disabled :p
joint_module: true
getrdn0: true
cmb_version: "apo_new_v2_no_alpha"
selected: ["a", "p", "o"] #ad would give a but disabled.
cmbchain: ["p"]
tol: 6
beam: 1.0
nlev_t: 1.0
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30
lmin_blm: 30
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
no_tau: true
no_curl: true
# Binning parameters
binning:
  lmin: 20
  lmax: 4000
  delta: 40