#This file has full set of effects in the observed CMB
#but it only reconstructs the rotation and lensing effects.
#the rotation effect is disabled as an operator
name: spt
title: '$[\widehat{\alpha}\widehat{\phi}]^{D}[\alpha, \phi]$'
k: "p_p"
itmax: 15
imin: 0
imax: 1
v: "apospt3g"
joint_module: true
do_mf: false
getrdn0: false
cmb_version: "apo_new"
selected: ["a", "p", "o"] #ad would give a but disabled.
cmbchain: ["a", "p"]
tol: 6
beam: 1.4
nlev_t: 1.6
lmax_ivf: 4000
mmax_ivf: 4000
lmin_elm: 30
lmin_blm: 30
lmax_unl: 4000
mmax_unl: 4000
lmax_qlm: 5000
mmax_qlm: 5000
#no_tau: true
#no_curl: true
# Binning parameters
binning:
  lmin: 20
  lmax: 4000
  delta: 40